### WelcomeMessage
GET http://localhost:8300/greeting-service/sayHello

### GoodbyeMessage

GET http://localhost:8300/greeting-service/sayGoodBye

### Refresh Properties
POST http://localhost:8300/greeting-service/actuator/refresh
