global:
  scrape_interval: 2s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gateway_service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']
        labels:
          service: gateway-service
  - job_name: 'greeting-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8300']
        labels:
          service: greeting-service
  - job_name: 'time-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8400']
        labels:
          service: time-service
  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8500']
        labels:
          service: catalog-service
  - job_name: 'auction-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
#    basic_auth:
#      username: 'metrics'
#      password: 'secretkey'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8600']
        labels:
          service: auction-service
