version: "3"
services:

  # Cloud Services

  mailtrap:
    image: dbck/mailtrap:1.0.0
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
    platform: linux/amd64

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: masterkey
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 4dm1n!
      KEYCLOAK_IMPORT: /data/realm-cloudbay.json
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres/postgres"
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: masterkey
    volumes:
      - ../keycloak/realm-cloudbay.json:/opt/keycloak/data/import/realm-cloudbay.json
    stdin_open: true
    tty: true
    ports:
      - "8200:8080"
      - "9080:9090"
    links:
      - postgres:postgres
      - mailtrap:mailtrap
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"

  # Observability

#  jaeger:
#    image: jaegertracing/all-in-one
#    ports:
#      - "5775:5775"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14268:14268"
#      - "14250:14250"
#      - "9411:9411"#

  grafana:
    image: grafana/grafana:8.2.6
    depends_on:
      - prometheus
#      - tempo
#      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - "../grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "../grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "../grafana/grafana.ini:/etc/grafana/grafana.ini"

#  loki:
#    image: grafana/loki:2.7.1
#    depends_on:
#      - "fluent-bit"
#    ports:
#      - "3200:3100"
#
#  fluent-bit:
#    image: grafana/fluent-bit-plugin-loki:2.7.1-amd64
#    platform: linux/amd64
#

  prometheus:
    image: prom/prometheus:v2.40.6
    ports:
      - "9099:9090"
    volumes:
      - "../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    stdin_open: true
    tty: true
#
#  tempo:
#    image: grafana/tempo
#    command: -config.file /etc/tempo-config.yml
#    ports:
#      - "3100:3100"
#      - "4317:4317"
#    volumes:
#      - "../tempo/tempo.yml:/etc/tempo-config.yml"
